version: "3.3"

services:
  db:
    build:
      context: ./db
      args:
        - PB_VERSION=0.14.1
    expose:
      - 8080
    ports:
      - 8543:8080
    volumes:
      - ./db/pb_data:/pb/pb_data

  client:
    build: ./client
    ports:
      - 80:3000
    expose:
      - 80
    depends_on:
      - db
